// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAJz9pAASQf8QfyHTkCwSe5PHtgY93zviM',
      appId: '1:192281411997:android:187feb9534f7af15796f74',
      messagingSenderId: '192281411997',
      projectId: 'indrayani-dfb85',
      // authDomain: 'ping-app-167fd.firebaseapp.com',
      storageBucket: "indrayani-dfb85.appspot.com");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJz9pAASQf8QfyHTkCwSe5PHtgY93zviM',
    appId: '1:192281411997:android:187feb9534f7af15796f74',
    messagingSenderId: '192281411997',
    projectId: 'indrayani-dfb85',
    storageBucket: 'indrayani-dfb85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJz9pAASQf8QfyHTkCwSe5PHtgY93zviM',
    appId: '1:192281411997:android:187feb9534f7af15796f74',
    messagingSenderId: '192281411997',
    projectId: 'indrayani-dfb85',
    storageBucket: 'indrayani-dfb85.appspot.com',
    iosBundleId: 'com.indrayani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJz9pAASQf8QfyHTkCwSe5PHtgY93zviM',
    appId: '1:192281411997:android:187feb9534f7af15796f74',
    messagingSenderId: '192281411997',
    projectId: 'indrayani-dfb85',
    storageBucket: 'indrayani-dfb85.appspot.com',
    iosBundleId: 'com.indrayani.RunnerTests',
  );
}
